<a href="https://colab.research.google.com/github/yukinaga/ai_programming/blob/main/lecture_03/02_matrix_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 行列の積
行列同士を掛け合わせる方法を学びます。人工知能で効率的な計算を行うために大事な操作です。

### 行列の積

行列積では、前の行列における行の各要素と、後の行列における列の各要素を掛け合わせて総和をとり、新しい行列の要素とします。  
左の行列の全ての行と、右の行列の全ての列の組み合わせで演算を行い、新たな行列を作ります。  
行列積の例を見ていきましょう。まず、行列$A$と$B$を次のように設定します。  

$$
   A = \left(
    \begin{array}{ccc}
      a_{11} & a_{12} & a_{13} \\
      a_{21} & a_{22} & a_{23} \\
    \end{array}
  \right)
$$ 

$$ 
   B = \left(
    \begin{array}{cc}
      b_{11} & b_{12} \\
      b_{21} & b_{22} \\
      b_{31} & b_{32} \\
    \end{array}
  \right)
$$ 

$A$は2x3の行列で、$B$は3x2の行列です。  
そして、$A$と$B$の積を次のように表します。

$$ 
   AB = \left(
    \begin{array}{ccc}
      a_{11} & a_{12} & a_{13} \\
      a_{21} & a_{22} & a_{23} \\
    \end{array}
  \right) 
  \left(
    \begin{array}{cc}
      b_{11} & b_{12} \\
      b_{21} & b_{22} \\
      b_{31} & b_{32} \\
    \end{array}
  \right) \\
 = \left(
    \begin{array}{ccc}
      a_{11}b_{11}+a_{12}b_{21}+a_{13}b_{31} & a_{11}b_{12}+a_{12}b_{22}+a_{13}b_{32} \\
      a_{21}b_{11}+a_{22}b_{21}+a_{23}b_{31} & a_{21}b_{12}+a_{22}b_{22}+a_{23}b_{32} \\
    \end{array}
  \right) \\
 = \left(
    \begin{array}{ccc}
      \sum\limits_{k=1}^3 a_{1k}b_{k1} & \sum\limits_{k=1}^3 a_{1k}b_{k2} \\
      \sum\limits_{k=1}^3 a_{2k}b_{k1} & \sum\limits_{k=1}^3 a_{2k}b_{k2} \\
    \end{array}
  \right)
$$ 

$A$の各行と$B$の各列の各要素を掛け合わせて総和をとり、新しい行列の各要素とします。  
上記の行列積には総和の記号$\Sigma$が登場していますが、行列積は積の総和を計算する際に大活躍します。  
人工知能では積の総和を頻繁に計算するので、行列積は欠くことができません。 

### 行列積の数値計算
それでは、試しに数値計算をしてみましょう。以下の行列$A$、$B$を考えます。

$$
   A  = \left(
    \begin{array}{ccc}
      0 & 1 & 2 \\
      1 & 2 & 3 \\
    \end{array}
  \right) \\
   B  = \left(
    \begin{array}{cc}
      2 & 1 \\
      2 & 1 \\
      2 & 1 \\
    \end{array}
  \right) \\
$$ 

これらの行列の行列積は、以下の通りに計算できます。

$$
AB = \left(
    \begin{array}{ccc}
      0 & 1 & 2 \\
      1 & 2 & 3 \\
    \end{array}
  \right) 
  \left(
    \begin{array}{cc}
      2 & 1 \\
      2 & 1 \\
      2 & 1 \\
    \end{array}
  \right) \\
= \left(
    \begin{array}{ccc}
      0\times 2+1\times 2+2\times 2 & 0\times 1+1\times 1+2\times 1 \\
      1\times 2+2\times 2+3\times 2 & 1\times 1+2\times 1+3\times 1 \\
    \end{array}
  \right) \\
= \left(
    \begin{array}{ccc}
      6 & 3 \\
      12 & 6 \\
    \end{array}
  \right)
$$ 

スカラーの積と異なり、行列積においては、前の行列と後ろの行列の交換は特定の条件を除きできません。  
そして、行列積を計算するためには、前の行列の列数と、後ろの行列の行数が一致していなければいけません。
例えば、前の行列の列数が3であれば、後ろの行列の行数は3である必要があります。 

### 行列積の一般化

行列積を、より一般的な形で記述します。以下は、l x mの行列$A$と、m x nの行列$B$の行列積です。

$$  \begin{aligned} \\
AB & = \left(
    \begin{array}{cc}
      a_{11} & a_{12} & \ldots & a_{1m} \\
      a_{21} & a_{22} & \ldots & a_{2m} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{l1} & a_{l2} & \ldots & a_{lm} \\
    \end{array}
  \right)
\left(
    \begin{array}{cccc}
      b_{11} & b_{12} & \ldots & b_{1n} \\
      b_{21} & b_{22} & \ldots & b_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      b_{m1} & b_{m2} & \ldots & b_{mn} \\
    \end{array}
  \right) \\
  & = \left(
    \begin{array}{cccc}
      \sum\limits_{k=1}^m a_{1k}b_{k1} & \sum\limits_{k=1}^m a_{1k}b_{k2} & \ldots & \sum\limits_{k=1}^m a_{1k}b_{kn} \\
       \sum\limits_{k=1}^m a_{2k}b_{k1} & \sum\limits_{k=1}^m a_{2k}b_{k2} & \ldots & \sum\limits_{k=1}^m a_{2k}b_{kn} \\
      \vdots & \vdots & \ddots & \vdots \\
      \sum\limits_{k=1}^m a_{lk}b_{k1} & \sum\limits_{k=1}^m a_{lk}b_{k2} & \ldots & \sum\limits_{k=1}^m a_{lk}b_{kn} \\
    \end{array}
  \right)
  \end{aligned}
$$

### 行列積の実装
行列積を全ての行と列の組み合わせで計算するのは大変ですが、Numpyのdot関数を用いれば、簡単に行列積を計算することができます。  

In [ ]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 
b = np.array([[2, 1],
              [2, 1],
              [2, 1]]) 

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


### 要素ごとの積（アダマール積）

行列の要素ごとの積は、アダマール積とも呼ばれており、行列の各要素を掛け合わせます。  
以下の行列$A$、$B$を考えましょう。

$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{cccc}
      a_{11} & a_{12} & \ldots & a_{1n} \\
      a_{21} & a_{22} & \ldots & a_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{m1} & a_{m2} & \ldots & a_{mn}
    \end{array}
  \right) \\
   B & = \left(
    \begin{array}{cccc}
      b_{11} & b_{12} & \ldots & b_{1n} \\
      b_{21} & b_{22} & \ldots & b_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      b_{m1} & b_{m2} & \ldots & b_{mn}
    \end{array}
  \right)
\end{aligned} $$ 

これらの行列の要素ごとの積は、演算子$\circ$を用いて次のように表すことができます。

$$
   A\circ B = \left(
    \begin{array}{cccc}
      a_{11}b_{11} & a_{12}b_{12} & \ldots & a_{1n}b_{1n} \\
      a_{21}b_{21} & a_{22}b_{22} & \ldots & a_{2n}b_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{m1}b_{m1} & a_{m2}b_{m2} & \ldots & a_{mn}b_{mn}
    \end{array}
  \right)
$$

例えば次ような場合、

$$ \begin{aligned} \\
   A  & = \left(
    \begin{array}{ccc}
      0 & 1 & 2 \\
      3 & 4 & 5 \\
      6 & 7 & 8
    \end{array}
  \right) \\
  B  & = \left(
    \begin{array}{ccc}
      0 & 1 & 2 \\
      2 & 0 & 1 \\
      1 & 2 & 0
    \end{array}
  \right)
\end{aligned}
$$

$A$と$B$の要素ごとの積は次のようになります。

$$ \begin{aligned} \\
  A\circ B  & = \left(
    \begin{array}{ccc}
      0\times 0 & 1\times 1 & 2\times 2 \\
      3\times 2 & 4\times 0 & 5\times 1 \\
      6\times 1 & 7\times 2 & 8\times 0
    \end{array}
  \right) \\
  & = \left(
    \begin{array}{ccc}
      0 & 1 & 4 \\
      6 & 0 & 5 \\
      6 & 14 & 0
    \end{array}
  \right)
\end{aligned}
$$

### 要素ごとの積の実装
要素ごとの積を、Numpyを用いて実装すると、以下のセルのようになります。  
要素ごとの演算にはスカラーの積の演算子`*`を使います。  

In [ ]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 
b = np.array([[0, 1, 2],
              [2, 0, 1],
              [1, 2, 0]]) 

print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


要素ごとの積を計算するためには、配列の形状が同じである必要があります。  
要素ごとの和には`+`、要素ごとの差には`-`、要素ごとの割り算には`/`を使います。

### 演習:
以下のセルで、行列aと行列bの行列積を求め、行列cと行列dの要素ごとの積を求めましょう。

In [ ]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 
b = np.array([[0, 1],
              [1, 2],
              [2, 3]]) 

# 行列積
print(np.dot(a, b))

c = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 
d = np.array([[0, 2, 0],
              [2, 0, 2],
              [0, 2, 0]]) 

# 要素ごとの積
print(c*d)

[[ 5  8]
 [ 8 14]]
[[ 0  2  0]
 [ 6  0 10]
 [ 0 14  0]]
