<a href="https://colab.research.google.com/github/yukinaga/ai_programming/blob/main/lecture_03/03_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 転置
転置により、行列の行と列を入れ替えます。人工知能のコードでは転置を頻繁に使います。

### 転置とは？

行列に対する重要な操作に、**転置**というものがあります。行列を転置することにより、行と列が入れ替わります。以下は転置の例ですが、例えば行列$A$の転置行列は$A^{\mathrm{T}}$と表します。  

$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      4 & 5 & 6 \\
    \end{array}
  \right) \\
   A^{\mathrm{T}} & = \left(
    \begin{array}{cc}
      1 & 4 \\
      2 & 5 \\
      3 & 6 \\
    \end{array}
  \right) \\
\end{aligned} $$ 

$$  \begin{aligned} \\
   B & = \left(
    \begin{array}{cc}
      a & b \\
      c & d \\
      e & f \\
    \end{array}
  \right) \\
   B^{\mathrm{T}} & = \left(
    \begin{array}{ccc}
      a & c & e \\
      b & d & f \\
    \end{array}
  \right) \\
\end{aligned} $$ 

### 転置の実装
Numpyにおいては、行列を表す配列名の後に`.T`を付けると転置されます。

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.T)  # 転置

[[1 4]
 [2 5]
 [3 6]]


### 転置と行列積の実装
以下は、Numpyの配列を転置し、行列積を計算している例です。配列名のあとに```.T```をつけると、転置行列になります。

In [ ]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]])  # 2x3
b = np.array([[0, 1, 2],
              [1, 2, 3]])  # 2x3 このままでは行列積ができない

# print(np.dot(a, b))  # エラー
print(np.dot(a, b.T))  # 転置により行列積が可能に

[[ 5  8]
 [ 8 14]]


上記のコードでは、行列`b`を転置することで行数が3になり、行列`a`の列数と一致するので行列積が可能になっています。  

### 演習:
以下のセルで行列aもしくは行列bを転置し、行列aと行列bの行列積を計算しましょう。

In [ ]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 
b = np.array([[0, 1, 2],
              [2, 3, 4]]) 

# 行列積
print(np.dot(a, b.T))

[[ 5 11]
 [ 8 20]]
